### ISSUE TITLE
Plans for the future

### ISSUE THREAD

**Issue by opensourcegeek** [seed-rs/styles_hooks#8]
This looks absolutely brilliant, especially the [extending seed](https://seed-style-hooks.netlify.app/extending_seed) section. I'm currently experimenting with Seed, I really like the idea of Seed generally but not sure how much I'd have to write things from scratch (like date pickers etc). I'm happy to write them, just don't want it all to go to waste in few months time. 

So, I'm thinking of creating any missing components that I need using seed-style. Should I go ahead with it as it stands or should I wait a bit longer? I still think I'll use Seed but may be not seed-style for now. 

It'd be good to know what are the plans for this library generally, will it be stand alone or will this be merged into seed itself? If it's merged into Seed itself then any new components will automatically be built on top of this abstraction perhaps?

**Comment by MartinKavik** [comment]
Hi, Seed Hooks (this library) was originally written by a Seed contributor @rebo. While I was trying to understand and rewrite it, I've written this [blog post](https://dev.to/martinkavik/moonzoon-dev-news-3-signals-react-like-hooks-optimizations-39lp#old-zoon-architecture) explaining how it works and related (dis)advantages. During the research, I found out I feel limited by The Elm Architecture and Seed/React hooks and HTML/CSS so I'm focusing now on the [MoonZoon](https://github.com/MoonZoon/MoonZoon) framework and writing production apps in MoonZoon instead of maintaining Seed. Seed has some active contributors but I assume they don't have capacity to do bigger changes or refactors needed to refactor and merge this library into Seed's code.

**Comment by opensourcegeek** [comment]
Interesting, thanks for getting back. I may have to just stick with known devil (react/typescript) for now and may be revisit the wasm approach later. Cheers anyway.
